---
name: "TER deployment"

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
    # The actual TER upload job
    ter-release:
        name: "TYPO3 TER release"

        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout"
                uses: actions/checkout@v2
            -   name: "Publish new version to TER"
                uses: tomasnorre/typo3-upload-ter@v2
                with:
                    api-token: ${{ secrets.TYPO3_API_TOKEN }}
