---
name: Test

on: [push, pull_request]

jobs:
    php-lint:
        name: "PHP linter"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: [7.2, 7.3, 7.4, 8.0, 8.1]
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: "Install PHP"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "${{ matrix.php-versions }}"
            - name: "Cache composer dependencies"
              uses: actions/cache@v1
              with:
                  path: ~/.composer/cache
                  key: php-${{ matrix.php-versions }}
                      -composer-${{ hashFiles('composer.json') }}
                  restore-keys: |
                      php-${{ matrix.php-versions }}-composer-
            - name: "Install composer dependencies"
              run: composer install --no-progress
            - name: "Run PHP lint"
              run: "composer run-script test-php-lint"
    php-cs-fixer:
        name: "PHP-CS-Fixer"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: [8.0]
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: "Install PHP"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "${{ matrix.php-versions }}"
            - name: "Cache composer dependencies"
              uses: actions/cache@v1
              with:
                  path: ~/.composer/cache
                  key: php-${{ matrix.php-versions }}
                      -composer-${{ hashFiles('composer.json') }}
                  restore-keys: |
                      php-${{ matrix.php-versions }}-composer-
            - name: "Install composer dependencies"
              run: composer install --no-progress
            - name: "Run PHP-CS-Fixer"
              run: "composer run-script test-php-cs-fixer"
    tests:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 2
            matrix:
                variants:
                    - {typo3: 9, testing: 4, php: 7.2}
                    - {typo3: 10, testing: 5, php: 7.3}
                    - {typo3: 10, testing: 5, php: 7.4}
                    - {typo3: 11, testing: 6, php: 7.4}
                    - {typo3: 11, testing: 6, php: 8.0}
                    - {typo3: 11, testing: 6, php: 8.1}

        name: "Run tests with PHP ${{ matrix.variants.php }}
          using TYPO3 ${{ matrix.variants.typo3 }}
          with testing framework version ${{ matrix.variants.testing }}"
        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.variants.php }}
                  extensions: xml, mbstring, curl

            - name: "Cache composer dependencies"
              uses: actions/cache@v1
              with:
                  path: ~/.composer/cache
                  key: php-${{ matrix.variants.php }}
                      -typo3-${{ matrix.variants.typo3 }}
                      -testing-${{ matrix.variants.testing }}
                      -composer-${{ hashFiles('composer.json') }}
                  restore-keys: |
                      php-${{ matrix.variants.php }}
                      -typo3-${{ matrix.variants.typo3 }}
                      -testing-${{ matrix.variants.testing }}composer-
                      php-${{ matrix.variants.php }}-typo3-

            - name: "Install composer dependencies"
              run: composer require typo3/minimal
                  "^${{ matrix.variants.typo3 }}"
                  typo3/testing-framework "^${{ matrix.variants.testing }}"
                  --prefer-dist --no-progress --no-suggest

            - name: "Run Unit tests"
              run: composer run-script test-unit
